// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQo6xv7krBpnvPxgZ5Kt0U1-ohM7J8hjY',
    appId: '1:224386364086:web:755354cb8c951526cd6c17',
    messagingSenderId: '224386364086',
    projectId: 'student-portal-db-4c021',
    authDomain: 'student-portal-db-4c021.firebaseapp.com',
    storageBucket: 'student-portal-db-4c021.firebasestorage.app',
    measurementId: 'G-P9LSEVF1XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8R_ZFVawtfP76GHqAVy4ilWoVwNDcCM',
    appId: '1:224386364086:android:90a8c505b56d50a3cd6c17',
    messagingSenderId: '224386364086',
    projectId: 'student-portal-db-4c021',
    storageBucket: 'student-portal-db-4c021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMnb0w9VtK486-WdV6KqCOKfCw3KlUQuA',
    appId: '1:224386364086:ios:43f7a77164e63d44cd6c17',
    messagingSenderId: '224386364086',
    projectId: 'student-portal-db-4c021',
    storageBucket: 'student-portal-db-4c021.firebasestorage.app',
    iosBundleId: 'com.example.mistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMnb0w9VtK486-WdV6KqCOKfCw3KlUQuA',
    appId: '1:224386364086:ios:43f7a77164e63d44cd6c17',
    messagingSenderId: '224386364086',
    projectId: 'student-portal-db-4c021',
    storageBucket: 'student-portal-db-4c021.firebasestorage.app',
    iosBundleId: 'com.example.mistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQo6xv7krBpnvPxgZ5Kt0U1-ohM7J8hjY',
    appId: '1:224386364086:web:6dc3e3eed5929d47cd6c17',
    messagingSenderId: '224386364086',
    projectId: 'student-portal-db-4c021',
    authDomain: 'student-portal-db-4c021.firebaseapp.com',
    storageBucket: 'student-portal-db-4c021.firebasestorage.app',
    measurementId: 'G-03HW4YTE2L',
  );
}
